apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-immo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-immo@sha256:ce866c90eb550fc544452309390341130c01fafc4667e4ce696dac9cc3dc964d
        name: my-nodejs
        resources: {}
status: {}
